add masks
InRedikaWB/ScheduleAggregator pull request #18
Opened 2021-02-23 16:16 UTC by VitalDikov

2021-02-23 20:20 UTC, s4xack reviewed
Ниже накидал по коду, но есть еще проблемки с самим интерфейсом:

1. Скролл расписания работает рывками, выглядит не очень юзабельно, хорошо бы повиксить.
2. Дни недели сейчас  сложно различимы визуально в списке.

2021-02-23 20:20 UTC, s4xack commented on ScheduleAggregator.UiLegacy/TableMasks.cs
> +        public string SubjectTitle = default;
String.Empty выглядит читаемей чем default

2021-02-23 20:20 UTC, s4xack commented on ScheduleAggregator.UiLegacy/MainWindow.xaml
> +                          Checked="EvenWeek_Checked"/>
Какая-то из недель явна должа быть выбрана по дефолту

2021-02-23 20:20 UTC, s4xack commented on ScheduleAggregator.UiLegacy/MainWindow.xaml.cs
> +        private TableMasks Masks = new TableMasks();
проблемочки с неймингом приватных полей
стоит придерживаться `private TypeName _name`

2021-02-23 20:40 UTC, InRedikaWB commented on ScheduleAggregator.UiLegacy/TableMasks.cs
> +        public string SubjectTitle = default;
Но это же другое. Дефолт - это налл.

2021-02-23 20:46 UTC, InRedikaWB requested changes

2021-02-23 20:46 UTC, InRedikaWB commented on ScheduleAggregator.UiLegacy/MainWindow.xaml.cs
> +        private void PutMasks()
Я бы разделил методы фильтрации и выставления в UI. Это можно потом переиспользовать. Например вынести в класс TableMasks метод.

2021-02-23 20:46 UTC, InRedikaWB commented on ScheduleAggregator.UiLegacy/MainWindow.xaml.cs
> +                    MaskedScheduleItems = MaskedScheduleItems.Where(l => l.Room == Masks.Room).ToList();
ToList смотриться немного не очень. Кажется, что это прям нарушает идеологию линков и перечислений. Можно их убрать.

2021-02-23 20:46 UTC, InRedikaWB commented on ScheduleAggregator.UiLegacy/TableMasks.cs
> +    public class TableMasks
Может в что-то тип фильтров переименовать?

2021-02-23 20:52 UTC, s4xack commented on ScheduleAggregator.UiLegacy/TableMasks.cs
> +        public string SubjectTitle = default;
исходный коммент выглядил по-другому, но я написал криво
крч предлагаю поменять на String.Empty

2021-02-24 08:19 UTC, VitalDikov commented on ScheduleAggregator.UiLegacy/TableMasks.cs
> +        public string SubjectTitle = default;
Мне кажется надо оставить так, потому что
там дальше по коду идёт сравнение и, по моему проверка поле == default, супер читабельна и сама за все говорит

2021-02-24 09:17 UTC, s4xack commented on ScheduleAggregator.UiLegacy/TableMasks.cs
> +        public string SubjectTitle = default;
Но пустое поле и есть дефолтное для нас поведение. С пустой строкой (она же в нашем случае маска для какого-то параметра) можно работать с null - нет.

2021-02-24 09:46 UTC, VitalDikov commented on ScheduleAggregator.UiLegacy/TableMasks.cs
> +        public string SubjectTitle = default;
Дефолтное поле это не маска, а флаг, который сигнализирует что тут что делать ничего не надо.

2021-02-24 12:10 UTC, InRedikaWB commented on ScheduleAggregator.UiLegacy/TableFiltres.cs
> +        public List<DaySchedule> PutMasks(List<DayScheduleDescriptor> descriptors)
Кажется, мы тут только фильтр теперь делаем, без пута.

2021-02-24 12:10 UTC, InRedikaWB commented on ScheduleAggregator.UiLegacy/TableFiltres.cs
> +            if (descriptors == null)
Если сюда приходит null, то лучше ошибку кинуть. Это не ок, что мы пытаемся фильтровать null, и не ок, что будем null возвращать.

2021-02-24 12:10 UTC, InRedikaWB commented on ScheduleAggregator.UiLegacy/TableFiltres.cs
> +                var MaskedScheduleItems = day.ScheduleItems;
Замени var на IEnumerable<> и убери ToList в if'ах.

2021-02-24 12:53 UTC, VitalDikov commented on ScheduleAggregator.UiLegacy/TableFiltres.cs
> +        public List<DaySchedule> PutMasks(List<DayScheduleDescriptor> descriptors)
вопрос в нейминге?

2021-02-24 13:32 UTC, InRedikaWB commented on ScheduleAggregator.UiLegacy/TableFiltres.cs
> +        public List<DaySchedule> PutMasks(List<DayScheduleDescriptor> descriptors)
Угу)

2021-02-24 13:50 UTC, InRedikaWB approved these changes

2021-02-24 15:16 UTC, merged