verify lesson creation
InRedikaWB/ScheduleAggregator pull request #24
Opened 2021-03-03 21:12 UTC by VitalDikov

Начал работоу над верификаторами

2021-03-03 21:43 UTC, InRedikaWB requested changes
Давай вместо ошибок возвращать Result (https://github.com/altmann/FluentResults), чтобы в ui не хендлить ошибки, а нормально можно было список всех проблем показать

2021-03-03 21:43 UTC, InRedikaWB commented on ScheduleAggregator.DataModels/Services/LessonService.cs
> +                throw new Exception("This teacher already has lesson in this time");
Для лекций сломается?

2021-05-17 13:19 UTC, hrrrrustic commented on ScheduleAggregator.DataModels/Services/LessonService.cs
> +                throw new Exception("This teacher already has lesson in this time");
Задушил человека...

2021-06-30 06:48 UTC, I-SER-I commented
@VitalDikov живой?

2021-06-30 07:10 UTC, FrediKats commented
@I-SER-I ну типа
![image](https://user-images.githubusercontent.com/22368203/123917332-55513900-d98b-11eb-9130-0871a11d766c.png)

2021-07-04 07:59 UTC, VitalDikov commented
@I-SER-I  живой

2021-09-05 15:36 UTC, annchous commented
Автор умер от депрессии

2021-09-05 15:36 UTC, closed without merging