Isu
InRedikaWB/ScheduleAggregator pull request #25
Opened 2021-03-05 18:26 UTC by VitalDikov

2021-03-06 18:18 UTC, s4xack requested changes
ну и следовательно неплохо было бы, если это все начнет реально работать и нормально парсить

2021-03-06 18:18 UTC, s4xack commented on ScheduleAggregator.DataModels/Services/ISUParser.cs
> +        }
почему эти 2 метода называются Get..., хотя остальные подобные им называются Convert...

2021-03-06 18:18 UTC, s4xack commented on ScheduleAggregator.DataModels/Services/ISUParser.cs
> +                    return;
странное поведение 
почему мы перестаем добавлять если у нас существует уже хотябы 1 корпус из тех, что предоставляет ИСУ
аналогичная проблема в других методах

2021-03-06 18:25 UTC, VitalDikov commented on ScheduleAggregator.DataModels/Services/ISUParser.cs
> +                    return;
стоит заменить return на continue. Мой косяк

2021-03-07 18:15 UTC, VitalDikov commented
Исправил недочёты и +- потестил. Вроде работает

2021-03-07 20:11 UTC, s4xack approved these changes

2021-03-07 20:11 UTC, merged