Шлифовка и исправление багов
InRedikaWB/ScheduleAggregator pull request #28
Opened 2021-03-07 21:47 UTC by VitalDikov

2021-03-07 21:52 UTC, s4xack requested changes

2021-03-07 21:52 UTC, s4xack commented on ScheduleAggregator.DataModels/Services/SemesterService.cs
> +            if (_uof.Semesters.Get(_ => _.Name == name).Any())
может сразу тогда и все эти `_` уберешь?)

2021-03-07 21:52 UTC, VitalDikov commented on ScheduleAggregator.DataModels/Services/SemesterService.cs
> +            if (_uof.Semesters.Get(_ => _.Name == name).Any())
так это полпроекта переделать....(ща уберу)

2021-03-07 21:54 UTC, s4xack commented on ScheduleAggregator.DataModels/Services/SemesterService.cs
> +            if (_uof.Semesters.Get(_ => _.Name == name).Any())
ctrl + h в помощь

2021-03-07 23:09 UTC, InRedikaWB commented on ScheduleAggregator.DataModels/Repositories/GenericRepository.cs
>          public IEnumerable<TEntity> Get(Func<TEntity, bool> predicate)
А почему бы не заюзать тут IQueryble?

2021-03-08 07:30 UTC, VitalDikov commented on ScheduleAggregator.DataModels/Repositories/GenericRepository.cs
>          public IEnumerable<TEntity> Get(Func<TEntity, bool> predicate)
![image](https://user-images.githubusercontent.com/71635718/110288487-24728000-7ff9-11eb-851a-fd9d9feb360e.png)
примерно поэтому. Сейчас сделаю да

2021-03-08 07:49 UTC, VitalDikov commented
Я так понимаю IEnumerable и IQueyrable взаимозаменяемы без каких либо проблем. По крайней мере никаких ошибок не выбилось

2021-03-08 10:01 UTC, InRedikaWB commented on ScheduleAggregator.DataModels/Repositories/GenericRepository.cs
> +            return (IQueryable<TEntity>)_dbSet.Where(predicate);
А почему тут каст? Что во что кастится? Это выглядит как совсем не ок

2021-03-08 10:16 UTC, VitalDikov commented on ScheduleAggregator.DataModels/Repositories/GenericRepository.cs
> +            return (IQueryable<TEntity>)_dbSet.Where(predicate);
по другому не получается
![image](https://user-images.githubusercontent.com/71635718/110307884-812d6500-8010-11eb-965a-f867aa4089d7.png)

2021-03-08 11:28 UTC, InRedikaWB approved these changes

2021-03-08 11:58 UTC, s4xack approved these changes

2021-03-08 11:58 UTC, merged